import type { Metadata } from "next";
import "./globals.css";
import { Web3Provider } from "./context/Web3Provider";
import { Header } from "./components/Header";

export const metadata: Metadata = {
  title: "Cryptotip",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen w-screen">
        <Web3Provider>
          <Header />
          <main className="flex flex-1 justify-center items-center">
            {children}
          </main>
        </Web3Provider>
      </body>
    </html>
  );
}
