import type { Metadata } from "next";
import "./globals.css";
import { Web3Provider } from "./context/Web3Provider";
import { Header } from "./components/Header";

export const metadata: Metadata = {
  title: "Cryptotip",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Web3Provider>
          <Header />
          <div className="flex justify-center items-center h-screen">
            {children}
          </div>
        </Web3Provider>
      </body>
    </html>
  );
}
